server:
  port: 8083

knife4j:
  enable: true
  openapi:
    title: 接口服务器
    description: "**接口服务器**"
    email: qqdas522@gmail.com
    concat: 邱
    url: http://localhost:8083/doc.html
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/